### ISSUE TITLE
Deploy as a lambda

### ISSUE THREAD

**Issue by tahpot** [verida/network-data-api#2]
@nick-verida Can you please make this work as a lambda and deploy to to https://data.verida.network

There is no need for this to be a testnet only deployment as the network name is in the DID and I've written it to use whatever network the DID specified.

**Comment by nick-verida** [comment]
Deployed as a Lambda from this branch: https://github.com/verida/network-data-api/tree/feature/2-deploy-as-lambda

Currently running at https://ipyrbh9qzh.execute-api.us-east-1.amazonaws.com/ on our testnet infrastructure. Need to work out what to call this.

**Comment by nick-verida** [comment]
This is now available at https://data.verida.network/
